---
title: "Compare_ebvaepm_ebpm"
author: "zihao12"
date: "2019-10-23"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---
Here I show and compare the results from `ebvae_pm` and `ebpmf`. `ebvae_pm` was implemented and experimented here: https://zihao12.github.io/ebpmf_demo/ebvae-poisson-normal.html . 

Now `ebvae_pm` does much  worse even than the `mle`. It seems to be shrinking too much. 

```{r warning=F}
devtools::load_all("../ebpm")
library(ggplot2)
library(reticulate)
```

## show VAE results
```{r}
vae_out = py_load_object("data/poisson-normal.pkl", pickle = "pickle")
vae_out = data.frame(vae_out)

## This is what data looks like
ggplot(vae_out)+
  geom_histogram(aes(x = x), bins = 100)

ggplot(vae_out)+
  geom_point(aes(x = x, y = posterior_vae))
```

## Compare with EBPM
```{r warning=F}
library(ebpm)
fit_ebpm = ebpm_exponential_mixture(as.vector(vae_out$x), s = 1, m = 2^0.25)
vae_out[["posterior_ebpm"]] = fit_ebpm$posterior$mean
ggplot(vae_out)+
  geom_point(aes(x = x, y = posterior_ebpm))
```


```{r}
## biggest weight
max(fit_ebpm$fitted_g$pi)
## the mean  of the exponential component corresponding to the biggest weight
fit_ebpm$fitted_g$scale[which.max(fit_ebpm$fitted_g$pi)]
```


## Compare RMSE
```{r}
## rmse(fit_vae, lam)
sqrt(mean((vae_out$posterior_vae - vae_out$lam)^2))

## rmse(fit_ebpm, lam)
sqrt(mean((fit_ebpm$posterior$mean - vae_out$lam)^2))

## rmse(mle, lam)
sqrt(mean((vae_out$x- vae_out$lam)^2))
```






