---
title: "demo_ebpmf_two_gamma"
author: "zihao12"
date: "2019-12-09"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r}
set.seed(123)
library(NNLM)
library(ebpmf.alpha)
```

## On Simulated Data 

### simulate data
```{r}
## sample L, F from mixture of two gammas
sample_from_two_gamma <- function(pi0, shape1, scale1, 
                                  shape2, scale2){
  if(rbinom(1, 1, pi0) == 1){return(rgamma(n = 1, shape = shape1, scale = scale1))}
  else{return(rgamma(n = 1, shape = shape2, scale = scale2))}
}

n = 100
p = 200
k = 2

pi0 = 0.75
shape1 = 1; scale1 = 1/10
shape2 = 10; scale2 = 1/2

L = matrix(replicate(n = n*k, sample_from_two_gamma(pi0, shape1, scale1, shape2, scale2)), ncol = k)
F = matrix(replicate(n = p*k, sample_from_two_gamma(pi0, shape1, scale1, shape2, scale2)), ncol = k)
lam = L %*% t(F)
X = matrix(rpois(n = n*p, lambda = lam), nrow= n)

print(sprintf("zero percentage: %f", sum(X == 0)/(n*p)))
hist(X, breaks = 50, main = "histogram of count matrix")
```

### fit with mle and ebpmf
```{r warning=FALSE, message=FALSE, cache=TRUE}
fit_mle = NNLM::nnmf(A = X, k = k, loss = "mkl", method = "lee", max.iter = 500)
fit_ebpmf_two_gamma = ebpmf_two_gamma(X = X, K = k, maxiter.out = 500)
```

### compare result
```{r}
lam_true = L %*% t(F)
lam_ebpmf_two_gamma = fit_ebpmf_two_gamma$qg$qls_mean %*% t(fit_ebpmf_two_gamma$qg$qfs_mean)
lam_mle = fit_mle$W %*% fit_mle$H

rmse <- function(true, est){
  return(sqrt(mean((true - est)^2)))
}
KL <- function(true,est){
  sum(ifelse(true==0,0,true * log(true/est)) + est - true)
}
JS  <- function(true,est){
  0.5*(KL(true, est) + KL(est, true))
}

lls = c(sum(dpois(x = X, lambda = lam_mle, log = T)), sum(dpois(x = X, lambda = lam_ebpmf_two_gamma, log = T)))
RMSEs = c(rmse(lam_true, lam_mle),  rmse(lam_true, lam_ebpmf_two_gamma))
KLs = c(KL(lam_true, lam_mle),  KL(lam_true, lam_ebpmf_two_gamma))
JSs = c(JS(lam_true, lam_mle),  JS(lam_true, lam_ebpmf_two_gamma))
data.frame(loglike = lls, RMSE = RMSEs, KL = KLs, JS = JSs, row.names = c("mle", "ebpmf_two_gamma"))
```
I compute the data loglikelihood, as well as the various divergence between true $\lambda$ and estimates $\hat{\lambda}$. From the result we can see MLE overfits the data too much; `ebpmf_two_gamma` is closer to the truth. 


