---
title: "Investigate_sparsity_ebpm"
author: "zihao12"
date: "2019-11-01"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r warning=F}
devtools::load_all("../ebpm")
library(ebpm)
library(ggplot2)
source("code/misc.R")

KL <- function(true,est){
  sum(ifelse(true==0,0,true * log(true/est)) + est - true)
}

JS  <- function(true,est){
  0.5*(KL(true, est) + KL(est, true))
}

RMSE <- function(true, est){
  sqrt(mean((true - est)^2))
}
```

## sparse  data
```{r}
set.seed(123)
n = 99
lam = replicate(n, 0)
lam[1:(n/3)] = 50
x = rpois(n, lambda = lam)
hist(x, breaks = 100)

fit_ebpm_exp = ebpm::ebpm_exponential_mixture(x, m = 2^0.25)

fit_ebpm_pg = ebpm::ebpm_point_gamma(x)
  
df = data.frame(idx = 1:length(x),x = x, exp = fit_ebpm_exp$posterior$mean, pg =  fit_ebpm_pg$posterior$mean)
ggplot(df)+
  geom_point(aes(x = x,   y = exp, color = "ebpm_exponential_mixture"))+
  geom_point(aes(x = x,   y = pg, color = "ebpm_point_gamma"))+
  geom_abline(slope = 1, intercept = 0)+
  ylab("posterior mean")
```

The $0$ are  fitted with:
```{r}
min(df$exp)
min(df$pg)
```


Let's take a closer look at those large elements
```{r warning=F}
df_large = df[1:(n/3),]
ggplot(df_large)+
  geom_point(aes(x = x,   y = exp, color = "ebpm_exponential_mixture"))+
  geom_point(aes(x = x,   y = pg, color = "ebpm_point_gamma"))+
  geom_abline(slope = 1, intercept = 0)+
  ylab("posterior mean")
```


Compare KL, Jensen-Shannon divergence and RMSE
```{r}
###### KL divergence
## MLE
KL(lam, df$x)
## exp
KL(lam, df$exp)
## pg
KL(lam, df$pg)

###### Jensen-Shannon divergence
## MLE
JS(lam, df$x)
## exp
JS(lam, df$exp)
## pg
JS(lam, df$pg)

###### RMSE
## MLE
RMSE(lam, df$x)
## exp
RMSE(lam, df$exp)
## pg
RMSE(lam, df$pg)
```

## look at $\hat{g}$
```{r}
m = 1000
point_df = data.frame(samples = sample_point_gamma(m, fit_ebpm_pg$fitted_g), method = "point_gamma")
exp_df   = data.frame(samples = sample_expmix(m, fit_ebpm_exp$fitted_g), method = "exponential_mixture")
samples_df = rbind(point_df, exp_df)
ggplot(samples_df, aes(samples, fill = method)) + geom_density(alpha = 0.2)+ggtitle("compare g_hat")
```










## not exactly sparse
replace 0 with small values in data. 
```{r warning=F}
set.seed(123)
mfac = 2 # controls PVE of dense factor
n = 99
lam = mfac*runif(n)
lam[1:(n/3)] = 50
x = rpois(n, lambda = lam)
hist(x, breaks = 100)

fit_ebpm_exp = ebpm::ebpm_exponential_mixture(x, m = 2^0.25)

fit_ebpm_pg = ebpm::ebpm_point_gamma(x)
  
df = data.frame(idx = 1:length(x),x = x, exp = fit_ebpm_exp$posterior$mean, pg =  fit_ebpm_pg$posterior$mean)
ggplot(df)+
  geom_point(aes(x = x,   y = exp, color = "ebpm_exponential_mixture"))+
  geom_point(aes(x = x,   y = pg, color = "ebpm_point_gamma"))+
  geom_abline(slope = 1, intercept = 0)+
  ylab("posterior mean")

min(df$x)
min(df$exp)
min(df$pg)
```


Let's take a closer look at those small elements
```{r warning=F}
df_small = df[-(1:(n/3)),]
ggplot(df_small)+
  geom_point(aes(x = x,   y = exp, color = "ebpm_exponential_mixture"))+
  geom_point(aes(x = x,   y = pg, color = "ebpm_point_gamma"))+
  geom_abline(slope = 1, intercept = 0)+
  ylab("posterior mean")
```


Let's take a closer look at those large elements
```{r warning=F}
df_large = df[1:(n/3),]
ggplot(df_large)+
  geom_point(aes(x = x,   y = exp, color = "ebpm_exponential_mixture"))+
  geom_point(aes(x = x,   y = pg, color = "ebpm_point_gamma"))+
  geom_abline(slope = 1, intercept = 0)+
  ylab("posterior mean")
```


Compare KL, Jensen-Shannon divergence and RMSE
```{r}
###### KL divergence
## MLE
KL(lam, df$x)
## exp
KL(lam, df$exp)
## pg
KL(lam, df$pg)

###### Jensen-Shannon divergence
## MLE
JS(lam, df$x)
## exp
JS(lam, df$exp)
## pg
JS(lam, df$pg)

###### RMSE
## MLE
RMSE(lam, df$x)
## exp
RMSE(lam, df$exp)
## pg
RMSE(lam, df$pg)
```

## look at $\hat{g}$
```{r}
m = 1000
point_df = data.frame(samples = sample_point_gamma(m, fit_ebpm_pg$fitted_g), method = "point_gamma")
exp_df   = data.frame(samples = sample_expmix(m, fit_ebpm_exp$fitted_g), method = "exponential_mixture")
samples_df = rbind(point_df, exp_df)
ggplot(samples_df, aes(samples, fill = method)) + geom_density(alpha = 0.2)+ggtitle("compare g_hat")
```












