---
title: "nmf_sparse_experiment2"
author: "zihao12"
date: "2020-03-06"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r}
rm(list = ls())
library(ggplot2)
source("code/misc.R")

data_old = readRDS("data/nmf_sparse1_data/nmf_sparse_data.Rds")
data = readRDS("data/nmf_sparse14_fitted.Rds")
X = data$X
L_true = data$L
F_true = data$F
L0 = data$init_lf$W
F0 = t(data$init_lf$H)

L0_old = data_old$LF0$W
F0_old = t(data_old$LF0$H)

fit_tg_slow = data$fit_tg
fit_pg = data$fit_pg
fit_gm0 = data$fit_gm0
fit_tg_fast5 = readRDS("data/nmf_sparse_ebpm_two_gamma_fast5.Rds")
fit_tg = readRDS("data/nmf_sparse_ebpm_two_gamma.Rds")
fit_gm = readRDS("data/nmf_sparse_ebpm_gamma_mixture2.Rds")
```

I run each method for 1000 iterations, except `tg_fast5`, which runs 5000 iterations. 

## show progress
```{r}
niter = 1000
elbos <- data.frame(x = seq(1,niter), tg_slow = fit_tg_slow$ELBO[1:niter], tg = fit_tg$ELBO[1:niter], 
                    tg_fast5 = fit_tg_fast5$ELBO[1:niter], pg = fit_pg$ELBO[1:niter], 
                    gm = fit_gm$ELBO[1:niter], gm0 = fit_gm0$ELBO[1:niter])
ggplot(data = elbos)+
  geom_line(aes(x = x, y = tg_slow, color = "tg_slow"))+
  geom_line(aes(x = x, y = tg, color = "tg"))+
  geom_line(aes(x = x, y = tg_fast5, color = "tg_fast5"))+
  geom_line(aes(x = x, y = pg, color = "pg"))+
  geom_line(aes(x = x, y = gm, color = "gm"))+
  geom_line(aes(x = x, y = gm0, color = "gm0"))+
  xlab("iter")+
  ylab("ELBO")
```


## compare divergence
```{r}
lam = data$L %*% t(data$F)
lam_tg_slow = fit_tg_slow$qg$qls_mean %*% t(fit_tg_slow$qg$qfs_mean)
lam_tg = fit_tg$qg$qls_mean %*% t(fit_tg$qg$qfs_mean)
lam_tg_fast = fit_tg_fast5$qg$qls_mean %*% t(fit_tg_fast5$qg$qfs_mean)
lam_pg = fit_pg$qg$qls_mean %*% t(fit_pg$qg$qfs_mean)
lam_gm = fit_gm$qg$qls_mean %*% t(fit_gm$qg$qfs_mean)
lam_gm0 = fit_gm0$qg$qls_mean %*% t(fit_gm0$qg$qfs_mean)

rmse = c(RMSE(lam, lam_tg_slow), RMSE(lam, lam_tg), 
         RMSE(lam, lam_tg_fast), RMSE(lam, lam_pg), 
         RMSE(lam, lam_gm), RMSE(lam, lam_gm0))

kl = c(KL(lam, lam_tg_slow), KL(lam, lam_tg), 
       KL(lam, lam_tg_fast), KL(lam, lam_pg),  
       KL(lam, lam_gm), KL(lam, lam_gm0))

js = c(JS(lam, lam_tg_slow), JS(lam, lam_tg), 
       JS(lam, lam_tg_fast), JS(lam, lam_pg), 
       JS(lam, lam_gm), JS(lam, lam_gm0))

maxiter = 1000
elbo = c(fit_tg_slow$ELBO[maxiter], fit_tg$ELBO[maxiter],
         fit_tg_fast5$ELBO[5000], fit_pg$ELBO[maxiter], 
         fit_gm$ELBO[maxiter], fit_gm0$ELBO[maxiter])

runtime = c(fit_tg_slow$runtime, fit_tg$runtime[[3]], 
         fit_tg_fast5$runtime[[3]], fit_pg$runtime, 
         fit_gm$runtime[[3]], fit_gm0$runtime)

data.frame(rmse = rmse, kl = kl, js = js, elbo = elbo, runtime = runtime,
           row.names = c("tg_slow", "tg", "tg_fast5", "pg", "gm", "gm0"))
```

## show loadings
```{r}
## truth
par(mfrow = c(2,2))
for(i in 1:4){plot(data$L[,i])}

# ## initialization
# par(mfrow = c(2,2))
# for(i in 1:4){plot(data$LF0$W[,i])}

##fit_tg_slow
par(mfrow = c(2,2))
for(i in 1:4){plot(fit_tg_slow$qg$qls_mean[,i], ylab = "loading", log = "y")}
##fit_tg
par(mfrow = c(2,2))
for(i in 1:4){plot(fit_tg$qg$qls_mean[,i], ylab = "loading", log = "y")}
##fit_tg_fast5
par(mfrow = c(2,2))
for(i in 1:4){plot(fit_tg_fast5$qg$qls_mean[,i], ylab = "loading", log = "y")}
##fit_pg
par(mfrow = c(2,2))
for(i in 1:4){plot(fit_pg$qg$qls_mean[,i], ylab = "loading", log = "y")}
##fit_gm
par(mfrow = c(2,2))
for(i in 1:4){plot(fit_gm$qg$qls_mean[,i], ylab = "loading", log = "y")}
##fit_gm0
par(mfrow = c(2,2))
for(i in 1:4){plot(fit_gm0$qg$qls_mean[,i], ylab = "loading", log = "y")}
```


### factor
```{r}
## truth
par(mfrow = c(2,2))
for(i in 1:4){plot(data$F[,i])}

# ## initialization
# par(mfrow = c(2,2))
# for(i in 1:4){plot(data$LF0$H[i,])}

##fit_tg_slow
par(mfrow = c(2,2))
for(i in 1:4){plot(fit_tg_slow$qg$qfs_mean[,i], ylab = "factor", log = "y")}
##fit_tg
par(mfrow = c(2,2))
for(i in 1:4){plot(fit_tg$qg$qfs_mean[,i], ylab = "factor", log = "y")}
##fit_tg_fast5
par(mfrow = c(2,2))
for(i in 1:4){plot(fit_tg_fast5$qg$qfs_mean[,i], ylab = "factor", log = "y")}
##fit_pg
par(mfrow = c(2,2))
for(i in 1:4){plot(fit_pg$qg$qfs_mean[,i], ylab = "factor", log = "y")}
##fit_gm
par(mfrow = c(2,2))
for(i in 1:4){plot(fit_gm$qg$qfs_mean[,i], ylab = "factor", log = "y")}
##fit_gm0
par(mfrow = c(2,2))
for(i in 1:4){plot(fit_gm0$qg$qfs_mean[,i], ylab = "factor", log = "y")}
```









